language: julia
julia:
    - release
    - nightly
notifications:
    email: false
before_install:
    - sudo apt-get update
    - sudo apt-get install cmake libgmp-dev libmpfr-dev
    - git config --global user.name "Isuru Fernando"
    - git config --global user.email "isuruf@gmail.com"
script:
    - git clone git@github.com:sympy/symengine.git
    - cd symengine
    - cmake .
    - sudo make install
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
    - cd ..
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("SymEngine")'
    - if [ -f test/runtests.jl ]; then
        julia --check-bounds=yes -e 'Pkg.test("SymEngine")'
      fi
